CREATE DATABASE MOV_CONTA_CORRENTE
GO

USE MOV_CONTA_CORRENTE
GO


-- Tabela de Históricos
CREATE TABLE Historicos (
    ID_HIS NUMERIC(4),
    DES_HIS VARCHAR(30),
	CONSTRAINT PK_HIS PRIMARY KEY (ID_HIS)
);

-- Tabela de Agências
CREATE TABLE Agencias (
    NUM_AGE NUMERIC(5) NOT NULL,
    NOME_AGE VARCHAR(30) NOT NULL,
    ENDE_AGE VARCHAR(50) NOT NULL,
    NUM_END_AGE VARCHAR(8),
    COMPL_AGE VARCHAR(20),
    BAIR_AGE VARCHAR(20),
    CIDA_AGE VARCHAR(30) NOT NULL,
    UF_AGE CHAR(2) NOT NULL,
    CEP_AGE CHAR(8)NOT NULL,
    FONE_AGE VARCHAR(13),
	CONSTRAINT PK_AGE PRIMARY KEY (NUM_AGE)
);

-- Tabela de Clientes
CREATE TABLE Clientes (
    ID_CLI NUMERIC(9) NOT NULL,
    NOME_CLI VARCHAR(50) NOT NULL,
    ENDE_CLI VARCHAR(50) NOT NULL,
    NUM_CLI INT,
    COMPL_CLI VARCHAR(20),
    BAIR_CLI VARCHAR(20),
    CIDA_CLI VARCHAR(30),
    UF_CLI CHAR(2) NOT NULL,
    CEP_CLI CHAR(8) NOT NULL,
    FONE_CLI VARCHAR(13),
    CPF_CLI CHAR(11) NOT NULL,
    DATA_NASC DATETIME NOT NULL,
    CNPJ_CLI CHAR(14) NOT NULL,
	CONSTRAINT PK_CLI PRIMARY KEY (ID_CLI)
);

-- Tabela de Conta Corrente
CREATE TABLE ContaCorrente (
    NUM_CC NUMERIC(10) NOT NULL,
	NUM_AGE NUMERIC(5) NOT NULL,
    ID_CLI NUMERIC(9) NOT NULL,
    SALDO DECIMAL(15,2) NOT NULL,
    FOREIGN KEY (NUM_AGE) REFERENCES Agencias(NUM_AGE),
    FOREIGN KEY (ID_CLI) REFERENCES Clientes(ID_CLI),
	CONSTRAINT PK_CC PRIMARY KEY (NUM_CC, NUM_AGE)
);


-- Tabela de Movimentação
CREATE TABLE Movimentacao (
	NUM_AGE NUMERIC(5) NOT NULL,
	NUM_CC NUMERIC(10) NOT NULL,
	DATA_MOV DATETIME NOT NULL,
	NUM_DOCTO VARCHAR(6) NOT NULL,
	DEB_CRED CHAR(1) NOT NULL,
	ID_HIS NUMERIC(4) NOT NULL,
	COMPL_HIS VARCHAR(30),
	VALOR DECIMAL(9,2) NOT NULL,
	SALDO DECIMAL(15,2) NOT NULL,
	FOREIGN KEY (NUM_AGE) REFERENCES Agencias(NUM_AGE),
	FOREIGN KEY (NUM_CC, NUM_AGE) REFERENCES ContaCorrente(NUM_CC, NUM_AGE),
	FOREIGN KEY (ID_HIS) REFERENCES Historicos(ID_HIS),
	CONSTRAINT PK_MOV PRIMARY KEY (NUM_AGE, NUM_CC, DATA_MOV, NUM_DOCTO)
)

 
-- Tabela de Usuário
CREATE TABLE Usuarios (
	ID_USUARIO VARCHAR(20) NOT NULL,
	SENHA VARCHAR(20) NOT NULL,
	NUM_AGE NUMERIC(5) NOT NULL,
	NUM_CC NUMERIC(10) NOT NULL,
	ID_CLI NUMERIC(9) NOT NULL,
	CONSTRAINT FK_USUARIO_CC FOREIGN KEY (NUM_CC, NUM_AGE) REFERENCES ContaCorrente(NUM_CC, NUM_AGE),
	CONSTRAINT FK_USUARIO_CLI FOREIGN KEY (ID_CLI) REFERENCES Clientes(ID_CLI),
	CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO)
)

